### ISSUE TITLE
Plugin Compatibility Issue with PS Plugin Template

### ISSUE THREAD

**Issue by efmcyrill** [pluginsandsnippets/widget-for-zendesk-chat-via-api#11]
There is a compatibility issue between Widget for Zendesk Chat via API Version 1.8 and PS Plugin Template Version 1.1.3

If both plugins are activated I get a blank screen. The issue is probably the same as this issue here
https://github.com/pluginsandsnippets/ps-plugin-template/issues/38

https://www.dev.stageps.pluginsandsnippets.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

<img width="1716" alt="Screenshot 2022-07-08 at 09 59 32" src="https://user-images.githubusercontent.com/6698575/177945828-b77728a2-b950-449a-990e-06355718ebe6.png">

**Comment by siawaahmed** [comment]
@efmcyrill 
The issue was with PS Plugin Template, the installation of updated version of that plugin has already fixed the issue.
