### ISSUE TITLE
Replacing Banner Image

### ISSUE THREAD

**Issue by efmcyrill** [pluginsandsnippets/widget-for-zendesk-chat-via-api#13]
https://wordpress.org/plugins/widget-for-zendesk-chat-via-api/

<img width="1086" alt="Screen Shot 2022-10-05 at 4 02 00 PM" src="https://user-images.githubusercontent.com/6698575/194079855-d76c6f57-a9ce-4f5b-8e9c-01467758e522.png">

We also need to replace this banner image with something which more plugin related

**Comment by ellerish-wp** [comment]
see here new icon and banner https://drive.google.com/drive/u/0/folders/1Tzdohul7_4VUmAQ59Z_roTLu79zBdnfj
