### ISSUE TITLE
Wording Changes

### ISSUE THREAD

**Issue by efmcyrill** [pluginsandsnippets/widget-for-zendesk-chat-via-api#20]
1. Instead of Zendesk Chat Settings settings, we should just call the menu "Zendesk Chat" so it prints on one line

<img width="176" alt="Screen Shot 2022-11-22 at 8 54 08 AM" src="https://user-images.githubusercontent.com/6698575/203256974-834e8e4d-bac3-418d-9b11-e7911d3f25ad.png">

2. Actually what is entered is the Zendesk Chat Account Key, not an API Key
https://support.zendesk.com/hc/en-us/articles/4408825772698-How-do-I-find-my-Chat-Account-Key

<img width="1717" alt="Screen Shot 2022-11-22 at 8 56 10 AM" src="https://user-images.githubusercontent.com/6698575/203257175-44acd79b-d182-44fc-91dd-451e50fe8287.png">

3.  On the settings page, the title in bold above the first input field we should rename from "Zendesk Chat API Code" to "**Zendesk Chat Account Key**"
=> This will avoid confusion if the account key is the same as the api key or not

4. "Zendesk Chat API Delay Time " we should rename to "**Zendesk Chat Widget Loading Delay Time**"
=> this will make it more clear that we delay the loading time of the widget

**Comment by napoleaowingert** [comment]
Done
